version: "3.3"

services:

  nginx:

    container_name: nginx

    image: nginx:alpine

    ports:

      - target: 80

        published: 80

        protocol: tcp

    volumes:

      - type: bind

        source: ./nginx.conf

        target: /etc/nginx/nginx.conf

    networks:

      - character-net
 
  

    networks:

      - "password-net"

  front-end:

    container_name: front-end

    image: benson700/front-end:latest

    build: ./front-end

    environment:

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}



    networks:

      - "password-net"

  service-2:

    image: benson700/service-2:latest

    build: ./service-2

    deploy:

      replicas: 3

    networks:

      - "password-net"

  service-3:

    image: benson700/service-3:latest

    build: ./service-3

    deploy:

      replicas: 3

    networks:

      - "password-net"

  service-4:

    image: benson700/service-4:latest

    build: ./service-4

    deploy:

      replicas: 3

    networks:

      - "password-net"

volumes:

  characters-vol:

networks:

  password-net: