version: "3.8"

services:

  nginx:

    container_name: nginx

    image: nginx:alpine

    ports:

      - target: 80

        published: 80

        protocol: tcp

    volumes:

      - type: bind

        source: ./nginx.conf

        target: /etc/nginx/nginx.conf

    networks:

      - character-net
 
  mysql:

    container_name: mysql

    image: benson700/password-db:latest

    build: ./password-db

    environment:

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      MYSQL_DATABASE: passworddb

    volumes:

      - type: volume

        source: characters-vol

        target: /var/lib/mysql

    networks:

      - "password-net"

  frontend:

    container_name: frontend

    image: benson700/frontend:latest

    build: ./frontend

    environment:

      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:

      - published: 80

        target: 5000

        protocol: tcp

    networks:

      - "password-net"

  service-2:

    image: benson700/service-2:latest

    build: ./service-2

    deploy:

      replicas: 3

    networks:

      - "password-net"

  service-3:

    image: benson700/service-3:latest

    build: ./service-3

    deploy:

      replicas: 3

    networks:

      - "password-net"

  service-4:

    image: benson700/service-4:latest

    build: ./service-4

    deploy:

      replicas: 3

    networks:

      - "password-net"

volumes:

  characters-vol:

networks:

  password-net: